# Generated by Django 4.2.1 on 2023-05-31 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IjaraUy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('Shaxar markazi', 'Shaxar markazi'), ('Shahar chekkasi', 'Shahar chekkasi'), ('Oliygoh yaqinida', 'Oliygoh yaqinida')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('room_size', models.PositiveIntegerField()),
                ('number_of_rooms', models.CharField(choices=[(1, '1 xona'), (2, '2 xona'), (3, '3 xona'), (4, '4 xona')], max_length=150, verbose_name='Xonalar Soni')),
                ('number_of_beds', models.CharField(choices=[(1, '1 yotoq'), (2, '2 yotoq'), (3, '3 yotoq'), (4, '4 yotoq')], max_length=150, verbose_name='Yotoqlar soni')),
                ('gender', models.CharField(choices=[('boys', 'Yigitlar'), ('girls', 'Qizlar'), ('mixed', 'Aralash')], max_length=150, verbose_name='Kim uchun')),
                ('kitchen', models.BooleanField(default=False, verbose_name='Oshxona')),
                ('tv', models.BooleanField(default=False, verbose_name='Televizior')),
                ('wifi', models.BooleanField(default=False, verbose_name='Wifi')),
                ('balcony', models.BooleanField(default=False, verbose_name='Balkon')),
                ('garage', models.BooleanField(default=False, verbose_name='Garaj')),
                ('bathroom', models.BooleanField(default=False, verbose_name='Hammom')),
                ('washing_machine', models.BooleanField(default=False, verbose_name='Kir yuvish mashinasi')),
                ('refrigerator', models.BooleanField(default=False, verbose_name='Konditsioner')),
                ('area_of_house', models.DecimalField(decimal_places=2, max_digits=6)),
                ('proximity_to_university', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Oliygohga_yaqinligi')),
                ('proximity_to_public_transportation', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='jamoat_transportiga_yaqinlik')),
            ],
        ),
    ]
