# Generated by Django 4.2.4 on 2023-08-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stuudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=25, verbose_name='Student ismi')),
                ('student_lastnem', models.CharField(max_length=25, verbose_name='Student familiyasi')),
                ('student_surname', models.CharField(max_length=25, verbose_name='Student otasining ismi')),
                ('student_brithday', models.DateTimeField(verbose_name="Tug'ilgan kuni")),
                ('student_state', models.CharField(max_length=150, verbose_name="Tug'ilgan davlati")),
                ('student_tuman', models.CharField(max_length=150, verbose_name='Tuman nomini kriting')),
                ('student_pasport', models.CharField(max_length=2, verbose_name='Pasport seriya')),
                ('student_pasportint', models.IntegerField(verbose_name='Pasport seriyasi')),
                ('student_adress', models.CharField(max_length=150, verbose_name='Yashash manzili')),
                ('student_phone', models.IntegerField(verbose_name='Telefon raqami')),
            ],
        ),
        migrations.CreateModel(
            name='Yotoqxona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yotoqxona_name', models.CharField(max_length=150, verbose_name='Yotoqxona nomi')),
                ('yotoqxona_rooms', models.IntegerField(verbose_name='Yotoqona xonalari')),
                ('yotoqxona_type', models.CharField(choices=[('girl', 'Girl'), ('boy', 'Boy')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='ijarauy',
            name='number_of_beds',
            field=models.CharField(choices=[('1', '1 yotoq'), ('2', '2 yotoq'), ('3', '3 yotoq'), ('4', '4 yotoq')], max_length=150, verbose_name='Yotoqlar soni'),
        ),
        migrations.AlterField(
            model_name='ijarauy',
            name='number_of_rooms',
            field=models.CharField(choices=[('1', '1 xona'), ('2', '2 xona'), ('3', '3 xona'), ('4', '4 xona')], max_length=150, verbose_name='Xonalar Soni'),
        ),
    ]
