# Generated by Django 4.2.4 on 2023-08-10 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yotoqxona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yotoqxona_name', models.CharField(max_length=150, verbose_name='Yotoqxona nomi')),
                ('yotoqxona_rooms', models.IntegerField(verbose_name='Yotoqona xonalari')),
                ('yotoqxona_type', models.CharField(choices=[('girl', 'Girl'), ('boy', 'Boy')], max_length=10)),
            ],
        ),
    ]
