# Generated by Django 4.2.4 on 2023-08-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_stuudents_yotoqxona_alter_ijarauy_number_of_beds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ijarauy',
            name='number_of_beds',
            field=models.CharField(choices=[(1, '1 yotoq'), (2, '2 yotoq'), (3, '3 yotoq'), (4, '4 yotoq')], max_length=150, verbose_name='Yotoqlar soni'),
        ),
        migrations.AlterField(
            model_name='ijarauy',
            name='number_of_rooms',
            field=models.CharField(choices=[(1, '1 xona'), (2, '2 xona'), (3, '3 xona'), (4, '4 xona')], max_length=150, verbose_name='Xonalar Soni'),
        ),
    ]
