# Generated by Django 4.2.4 on 2023-08-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_yotoqxona'),
    ]

    operations = [
        migrations.CreateModel(
            name='stuudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=25, verbose_name='Student ismi')),
                ('student_lastnem', models.CharField(max_length=25, verbose_name='Student familiyasi')),
                ('student_surname', models.CharField(max_length=25, verbose_name='Student otasining ismi')),
                ('student_brithday', models.DateTimeField(verbose_name="Tug'ilgan kuni")),
                ('student_state', models.CharField(max_length=150, verbose_name="Tug'ilgan davlati")),
                ('student_tuman', models.CharField(max_length=150, verbose_name='Tuman nomini kriting')),
                ('student_pasport', models.CharField(max_length=2, verbose_name='Pasport seriya')),
                ('student_pasportint', models.IntegerField(verbose_name='Pasport seriyasi')),
                ('student_adress', models.CharField(max_length=150, verbose_name='Yashash manzili')),
                ('student_phone', models.IntegerField(verbose_name='Telefon raqami')),
            ],
        ),
    ]
