# Generated by Django 4.2.4 on 2023-08-02 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_room_student_delete_ijarauy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='occupied_seats',
        ),
        migrations.AlterField(
            model_name='student',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.room'),
        ),
    ]
