# Generated by Django 4.2.4 on 2023-08-24 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ariza_home_stuudents_test_yotoqxona_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ariza',
            name='is_approved',
        ),
    ]
