# Generated by Django 4.2.4 on 2023-08-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_ariza_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yotoqxonalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Yotoqxona nomi')),
                ('image', models.ImageField(upload_to='yotoqxona/')),
                ('sigm', models.IntegerField(verbose_name="Yotoqxona sig'imi")),
            ],
        ),
        migrations.DeleteModel(
            name='Yotoqxona',
        ),
    ]
