# Generated by Django 4.2.4 on 2023-08-21 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_ijarauy_number_of_beds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ijarauy',
            name='number_of_beds',
            field=models.CharField(choices=[('1 yotoq', '1 yotoq'), ('2 yotoq', '2 yotoq'), ('3 yotoq', '3 yotoq'), ('4 yotoq', '4 yotoq')], max_length=150, verbose_name='Yotoqlar soni'),
        ),
        migrations.AlterField(
            model_name='ijarauy',
            name='number_of_rooms',
            field=models.CharField(choices=[('1 xona', '1 xona'), ('2 xona', '2 xona'), ('3 xona', '3 xona'), ('4 xona', '4 xona')], max_length=150, verbose_name='Xonalar Soni'),
        ),
    ]
