# Generated by Django 4.2.4 on 2023-08-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_ijarauy_number_of_beds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shahar', models.CharField(max_length=150, verbose_name='Shahar nomi')),
                ('Mahallasi', models.CharField(max_length=150, verbose_name='Mahalla nomi')),
                ('Manzil', models.CharField(max_length=150, verbose_name='Manzili')),
                ('Ijarachi', models.CharField(max_length=150, verbose_name='Ijarachining ismi')),
                ('Telefon', models.CharField(max_length=150, verbose_name='Telefon raqami')),
                ('Yigit', models.CharField(max_length=150, verbose_name='Yigitlar uchun')),
                ('Qiz', models.CharField(max_length=150, verbose_name='Qizlar uchun')),
                ('Holati', models.CharField(max_length=150, verbose_name='Ijara holati')),
            ],
        ),
    ]
