# Generated by Django 4.2.4 on 2023-08-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_yotoqxonalar_delete_yotoqxona'),
    ]

    operations = [
        migrations.AddField(
            model_name='yotoqxonalar',
            name='about',
            field=models.CharField(default=1, max_length=150, verbose_name='Yotoqxona xaqida'),
            preserve_default=False,
        ),
    ]
