# Generated by Django 4.2.4 on 2023-08-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_yotoqxonalar_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ariza',
            name='pasport',
            field=models.CharField(max_length=2, verbose_name='pasport seriya'),
        ),
        migrations.AlterField(
            model_name='ariza',
            name='pasport_num',
            field=models.IntegerField(verbose_name='Pasport raqami'),
        ),
    ]
