# Generated by Django 4.2.4 on 2023-08-29 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_ariza_pasport_alter_ariza_pasport_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ariza',
            name='uploaded_file',
        ),
    ]
