# Generated by Django 4.2.4 on 2023-08-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_home_holati_alter_home_ijarachi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='Holati',
            field=models.CharField(max_length=150, null=True, verbose_name='Ijara holati'),
        ),
        migrations.AlterField(
            model_name='home',
            name='Ijarachi',
            field=models.CharField(max_length=150, null=True, verbose_name='Ijarachining ismi'),
        ),
        migrations.AlterField(
            model_name='home',
            name='Mahallasi',
            field=models.CharField(max_length=150, null=True, verbose_name='Mahalla nomi'),
        ),
        migrations.AlterField(
            model_name='home',
            name='Manzil',
            field=models.CharField(max_length=150, null=True, verbose_name='Manzili'),
        ),
        migrations.AlterField(
            model_name='home',
            name='Qiz',
            field=models.CharField(max_length=150, null=True, verbose_name='Qizlar uchun'),
        ),
        migrations.AlterField(
            model_name='home',
            name='Shahar',
            field=models.CharField(max_length=150, null=True, verbose_name='Shahar nomi'),
        ),
        migrations.AlterField(
            model_name='home',
            name='Telefon',
            field=models.CharField(max_length=150, null=True, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='home',
            name='Yigit',
            field=models.CharField(max_length=150, null=True, verbose_name='Yigitlar uchun'),
        ),
    ]
