# Generated by Django 4.2.4 on 2023-08-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_ariza_uploaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ariza',
            name='telefon',
            field=models.IntegerField(verbose_name='Telefon raqam'),
        ),
    ]
