# Generated by Django 4.2.4 on 2023-08-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_home_holati_alter_home_ijarachi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_image', models.ImageField(upload_to='ijara/')),
            ],
        ),
    ]
