# Generated by Django 4.2.4 on 2023-08-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ariza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=15, verbose_name='Ismi')),
                ('familiya', models.CharField(max_length=20, verbose_name='Familiyasi')),
                ('sharifi', models.CharField(max_length=20, verbose_name='Otasining ismi')),
                ('viloyat', models.CharField(choices=[('tashkent', 'Tashkent'), ('samarkand', 'Samarkand'), ('bukhara', 'Bukhara'), ('andijan', 'Andijan'), ('ferghana', 'Ferghana'), ('namangan', 'Namangan'), ('navoiy', 'Navoiy'), ('surkhandarya', 'Surkhandarya'), ('jizzakh', 'Jizzakh'), ('kashkadarya', 'Kashkadarya'), ('sirdaryo', 'Sirdaryo'), ('khorezm', 'Khorezm'), ('karakalpakstan', 'Karakalpakstan')], max_length=100, verbose_name='Region')),
                ('tuman', models.CharField(max_length=30, verbose_name='Tuman nomini kriting')),
                ('jinsi', models.CharField(choices=[('erkak', 'Erkak'), ('ayol', 'Ayol')], max_length=15, verbose_name='Jinsini tanlang')),
                ('pasport', models.CharField(max_length=2, verbose_name='pasport seriya')),
                ('pasport_num', models.IntegerField(verbose_name='Pasport raqami')),
                ('manzil', models.CharField(max_length=150, verbose_name='Yashash manzili')),
                ('fakultet', models.CharField(choices=[('matematika va informatika', 'Matematika va Informatika'), ('rus va qozoq filialogiyasi', 'Rus va Qozoq filialogiyasi'), ('tarix', 'Tarix'), ('ingliz tili va adabioti', 'Ingliz tili va Adabioti'), ('jismoniy madaniyat', 'Jismoniy Madaniyat'), ("sa'atshunoslik", "Sa'atshunoslik"), ('tibbiyot', 'Tibbiyot')], max_length=150, verbose_name='Fakultetni tanlang')),
                ('yunlaish', models.CharField(max_length=150, verbose_name='yunalishni kriting')),
                ('grux', models.CharField(max_length=30, verbose_name='grux nomi')),
                ('kurs', models.CharField(choices=[('1kurs', '1 Kurs'), ('2kurs', '2 Kurs'), ('3kurs', '3 Kurs'), ('4kurs', '4 Kurs')], max_length=15, verbose_name='Fakultetni tanlang')),
                ('telefon', models.IntegerField(verbose_name='Telefon raqam')),
                ('uploaded_file', models.FileField(upload_to='xujjatlar/')),
            ],
        ),
    ]
