# Generated by Django 4.2.4 on 2023-09-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_ariza_telefon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ariza',
            options={'verbose_name': 'Ariza', 'verbose_name_plural': 'Arizalar'},
        ),
        migrations.AddField(
            model_name='ariza',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
