# Generated by Django 4.2.4 on 2023-08-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_ariza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ariza',
            name='kurs',
            field=models.CharField(choices=[('1kurs', '1 Kurs'), ('2kurs', '2 Kurs'), ('3kurs', '3 Kurs'), ('4kurs', '4 Kurs')], max_length=15, verbose_name='kursni tanlang'),
        ),
    ]
