# Generated by Django 4.2.4 on 2023-08-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_ariza_kurs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ariza',
            old_name='yunlaish',
            new_name='yunalish',
        ),
        migrations.AddField(
            model_name='ariza',
            name='mamlakat',
            field=models.CharField(choices=[('uzbekistan', "O'zbekistan"), ('india', 'India'), ('kazakhstan', 'Kazakhstan'), ('kyrgyzstan', 'Kyrgyzstan'), ('tajikistan', 'Tajikistan'), ('afganistan', 'Afganistan')], default=1, max_length=100, verbose_name='Region'),
            preserve_default=False,
        ),
    ]
